package com.helpschool.jhs.persistence;
// Generated 16-abr-2014 21:22:40 by Hibernate Tools 3.6.0



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private int name;
     private int password;

    public Users() {
    }

    public Users(int name, int password) {
       this.name = name;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getName() {
        return this.name;
    }
    
    public void setName(int name) {
        this.name = name;
    }
    public int getPassword() {
        return this.password;
    }
    
    public void setPassword(int password) {
        this.password = password;
    }




}


